name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH and Deploy
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ubuntu
        run: |
          # Ensure correct key format
          echo "$PRIVATE_KEY" | tr -d '\r' > private_key.pem
          chmod 600 private_key.pem

          # Add the host to known_hosts to avoid prompts
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

          # Connect and deploy
          ssh -i private_key.pem $USER@$HOST <<EOF
            cd /home/ubuntu/app
            git pull origin main
            npm install
            pm2 restart all
          EOF

