name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH and Test Connection
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ubuntu
        run: |
          echo "$PRIVATE_KEY" > git-action.pem
          chmod 600 git-action.pem
          ssh -o StrictHostKeyChecking=no -i git-action.pem $USER@$HOST "echo '✅ GitHub Actions SSH Successful'"
