      - name: Setup SSH and Test Connection
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ubuntu
        run: |
          # Ensure correct key format
          echo "$PRIVATE_KEY" | awk '{gsub(/\\n/,"\n")}1' > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST "echo '✅ GitHub Actions SSH Successful'"
